### PR TITLE
allow to use file_picker_callback and file_browser_callback

### PR DESCRIPTION
**Pull request by nykopol**

### CODE REVIEW

**Comment by Ingannatore** [comment]
Is this basically another "adding missing configuration options" change?

**Comment by nykopol** [comment]
The changes in init.*.js allow to pass this two parameters that where never transmitted to TinyMCE.
The change in the twig function is required as the values of this parameters are javascript function. So we have to remove the quotes to treat them as js function instead of simple string.

**Comment by Ingannatore** [comment]
Thanks a lot for the explanation :)
Did you already test those changes?

**Comment by nykopol** [comment]
yes

**Pull request merged**
