### PR TITLE
Outsource TinyMCE

### PR DESCRIPTION
**Pull request by MisatoTremor**
- Add tinymce/tinymce as requirement to composer.json
- Move TinyMCE languages to own directory
- Update language file handling to check for existing default territory expansion
- Remove embedded TinyMCE

Similar to how [MopaBootstrapBundle](http://github.com/phiamo/MopaBootstrapBundle) handles this:
- Add symlink and mirror commands for external TinyMCE
- Add symlink and mirror script handler for composer

Also see stfalcon/TinymceBundle#139

### CODE REVIEW

**Comment by Ingannatore** [comment]
Why did you add the `/Resources/public/vendor/tinymce` folder to `.gitignore`? That folder should not be present anymore after the outsourcing, right?

**Comment by RubenHarms** [comment]
@ingannatore That folder is used for Symlinking, so it should be ignored. On environments like Windows, the folder is used for hard copy. @MisatoTremo correct me if I'm wrong.

I Love this PR (+1)

**Comment by MisatoTremor** [comment]
Yes :)

**Comment by MisatoTremor** [comment]
I rebased the branch on this forks master.

Also fixed whitespace error in composer.json (some lines now hat tabs instead of spaces).

@Ingannatore I removed all the IDE and system specific and obsolete rules from .gitignore. You should always add them to your computers global .gitignore instead. If all people working on a project would add theirs, it would needlessly bloat the project .gitignore. :D

**Comment by zanardigit** [comment]
I agree with the idea of removing specific IDE settings from the project `.gitignore` file. @Ingannatore unless you have anything to add, I'm merging this. I'll wait until Monday.

**Comment by Ingannatore** [comment]
@MisatoTremor: you're totally right; I always forget about the global `.gitignore` :D

@zanardigit: everything is ok for me; see you on monday!

**Comment by MisatoTremor** [comment]
@zanardigit Would you please consider tagging this as a release, so it can be used as a version constraint?

Edit: After #3 has been merged.

**Comment by zanardigit** [comment]
Sure, we plan to create an actual release once some minor issues have been fixed.

**Pull request merged**
