### PR TITLE
add tinymce options : convert_urls, relative_urls, document_base_url

### PR DESCRIPTION
**Pull request by nykopol**
I added this 3 options because i needed this in hurry, but we should probably think about something more global for the future. Maybe an open parameter that would be passed as is to tinyMce.

### CODE REVIEW

**Comment by zanardigit** [comment]
Thanks @nykopol I will review this as soon as possible.

**Comment by Ingannatore** [comment]
Did you already test these changes (both on Sf 3.x and on Sf 2.x)?

> Maybe an open parameter that would be passed as is to tinyMce.

You read my mind :)

**Comment by nykopol** [comment]
@Ingannatore i tested it on 2.7 and it's working. From my experience, this changes are compatible from at least 2.3 to 2.8. For the compatibility again 3.\* according to the upgrade documentation, the Config component has only small changes that does not affect this modifications, so i think that it's compatible with 3.\* to.

**Comment by zanardigit** [comment]
@nykopol Symfony 3.0 is just 2.8 without deprecated features, so if you can test on 2.8 and make sure you have no deprecated that would be great.

The JS changes are obviously not related to Symfony version so I'm already ok with those.

`scalarNode` and `defaultNull` are there since at least Symfony 2.0 so backward compatibility is ok as well.

**Comment by nykopol** [comment]
I confirm that it's work on 2.8 without deprecation.

**Comment by nykopol** [comment]
can you please tag a new version that contain this PR ?

**Comment by Ingannatore** [comment]
Done: tagged as 1.2.0.

**Comment by nykopol** [comment]
thanks a lot

**Pull request merged**
